### ISSUE TITLE
Remove `wheel`

### ISSUE THREAD

**Issue by agriyakhetarpal** [agriyakhetarpal/hugo-python-distributions#117]
Based on https://github.com/pypa/setuptools/pull/4369 and have to bump `setuptools`'s version

**Comment by webknjaz** [comment]
> have to bump `setuptools`'s version

FTR, `wheel` never needed to be listed explicitly as it was being injected as a dependency automatically anyway.

**Comment by agriyakhetarpal** [comment]
Actually, it was – I imported the `bdist_wheel` class from `wheel` directly, and not having that would cause a `ModuleNotFoundError`? `python -m build` _might_ have worked, yes (never tried), but editable installations would break for me when I did this.
